[package]
name = "update-data"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]

[features]
# default = ["inline"]
inline = []
